#!/usr/bin/env python3
"""
check_cuda_layout.py — make the compiler prove that the CUDA kernels read
ForgeUniforms exactly where the Linux host writes it.

The host fills ForgeUniforms from the unmodified CyanescentForge/Shaders/
ForgeShaderTypes.h with Metal-layout vectors (src/ForgeHostTypes.hpp). The
kernels compile the same header inside namespace forge_gpu with their own
Metal-layout vectors (cuda/ForgeCUDACompat.cuh). This script:

  1. parses the field lists of ForgeQuality, ForgeSceneParams and
     ForgeUniforms from ForgeShaderTypes.h (as the Vulkan-era check_layout.py
     did),
  2. compiles and runs a probe printing sizeof/offsetof of every field with
     the host types,
  3. writes a header of static_asserts on forge_gpu::<struct> with those
     numbers.

The build includes that header (-DFORGE_LAYOUT_ASSERTS=...) in
cuda/CUDABackend.cu — so nvcc checks every offset in its *device* compilation
pass, with no GPU needed — and in cuda/CPUEmulationBackend.cpp.

Usage: check_cuda_layout.py <c++ compiler> <scratch dir> <output header>
Standard library only.
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
LINUX = os.path.dirname(HERE)
ROOT = os.path.normpath(os.path.join(LINUX, "..", "..", ".."))
HEADER = os.path.join(ROOT, "CyanescentForge", "Shaders", "ForgeShaderTypes.h")
STRUCTS = ["ForgeQuality", "ForgeSceneParams", "ForgeUniforms"]
FIELD = re.compile(r"^\s*(ForgeInt|ForgeUInt|float|ForgeVec2|ForgeVec3|ForgeVec4|ForgeQuality|ForgeSceneParams)\s+(\w+)\s*;")


def c_fields():
    text = open(HEADER).read()
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"//[^\n]*", "", text)
    result = {}
    for name in STRUCTS:
        m = re.search(r"typedef\s+struct\s*\{([^{}]*)\}\s*" + name + r"\s*;", text)
        if not m:
            sys.exit(f"check_cuda_layout: struct {name} not found in {HEADER}")
        fields = []
        for line in m.group(1).splitlines():
            f = FIELD.match(line)
            if f:
                fields.append(f.group(2))
            elif line.strip():
                sys.exit(f"check_cuda_layout: cannot parse field line in {name}: {line.strip()!r}")
        result[name] = fields
    return result


def host_offsets(fields, cxx, scratch):
    src = os.path.join(scratch, "cuda_layout_probe.cpp")
    exe = os.path.join(scratch, "cuda_layout_probe")
    with open(src, "w") as f:
        f.write('#include "%s"\n#include <cstdio>\n#include <cstddef>\nint main() {\n'
                % os.path.join(LINUX, "src", "ForgeHostTypes.hpp"))
        for struct, names in fields.items():
            f.write(f'    std::printf("{struct} sizeof %zu\\n", sizeof({struct}));\n')
            for n in names:
                f.write(f'    std::printf("{struct} {n} %zu\\n", offsetof({struct}, {n}));\n')
        f.write("    return 0;\n}\n")
    subprocess.run([cxx, "-std=c++17", "-o", exe, src], check=True)
    out = subprocess.run([exe], check=True, capture_output=True, text=True).stdout
    offsets = {s: {} for s in STRUCTS}
    for line in out.splitlines():
        struct, name, value = line.split()
        offsets[struct][name] = int(value)
    return offsets


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    cxx, scratch, output = sys.argv[1:]
    os.makedirs(scratch, exist_ok=True)
    fields = c_fields()
    host = host_offsets(fields, cxx, scratch)
    lines = [
        "// Generated by Tools/ForgeRenderWorker/Linux/tools/check_cuda_layout.py — do not edit.",
        "// Host (Metal-layout) offsets of every ForgeShaderTypes.h field, asserted on the kernels' structs.",
        "#include <cstddef>",
    ]
    for struct in STRUCTS:
        size = host[struct]["sizeof"]
        lines.append(f'static_assert(sizeof(forge_gpu::{struct}) == {size}, '
                     f'"forge_gpu::{struct} size differs from the host ({size} bytes)");')
        for name in fields[struct]:
            off = host[struct][name]
            lines.append(f'static_assert(offsetof(forge_gpu::{struct}, {name}) == {off}, '
                         f'"forge_gpu::{struct}.{name} is not at host offset {off}");')
    with open(output, "w") as f:
        f.write("\n".join(lines) + "\n")
    counted = sum(len(fields[s]) for s in STRUCTS)
    print(f"Layout: {counted} ForgeShaderTypes.h fields asserted for the kernels "
          f"(ForgeUniforms {host['ForgeUniforms']['sizeof']} bytes, Metal layout).")


if __name__ == "__main__":
    main()
